---
name: Feature request
description: Suggest new features or improvements to existing features
labels:
  - "feature-request"
title: "[Feature-request]: "
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please check the issues tab to avoid duplicates.
        Thanks for providing feedback!
  - type: textarea
    attributes:
      label: Describe the desired feature or improvement
      description: Please be as specific as you can, explain why is that needed or what problem it solves.
    validations:
      required: true
